"""Create tables

Revision ID: 663d437a0df4
Revises: b8c5aff5720b
Create Date: 2022-09-06 21:04:10.321897

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "663d437a0df4"
down_revision = "b8c5aff5720b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    oil_types = op.create_table(
        "oil_types",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oil_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        oil_types,
        [
            {"id": 1, "created_at": datetime.now(), "updated_at": datetime.now(), "oil_type": "ハイオク"},
            {"id": 2, "created_at": datetime.now(), "updated_at": datetime.now(), "oil_type": "レギュラー"},
        ],
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oil_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("survey_date", sa.Date(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("ref_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oil_type_id"],
            ["oil_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prices")
    op.drop_table("oil_types")
    # ### end Alembic commands ###
